name: build and push

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v7

      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: |
            ghcr.io/cars10/elasticvue.com:latest

      - name: deploy
        run: |
          curl -X POST https://autodok.cars10k.de/update \
            -H "Content-Type: application/json" \
            -H "Authorization: ${{ secrets.AUTODOK_API_KEY }}" \
            -d '{"container": "elasticvue_com", "image": "ghcr.io/cars10/elasticvue.com"}'
